name = "homepage"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "leekeh-comments"
database_id = "4569645d-ef03-4e5c-84f7-dab3fe3f35f3"
remote = true
