name: Post-deployment statistics

env:
  LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  deployment_status:
jobs:
  generate_lighthouse_audit:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        id: lighthouseScore
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ github.event.deployment_status.target_url }}
          temporaryPublicStorage: true
          configPath: '.github/lighthouse/assertions.json'
      - run: echo "${{steps.lighthouseScore.outputs}}" >> $GITHUB_STEP_SUMMARY
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ steps.findPr.outputs.pr }}
          message: |
            ### Lighthouse Audit Results
            - Accessibility Score: ${{ steps.lighthouseScore.outputs.manifest[0].summary.performance }}
