on:
  push:
    branches:
      - main

jobs:
  update-branches:
    name: Automatically update branches
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
